### ISSUE TITLE
Solution does not build

### ISSUE THREAD

**Issue by EPTamminga** [DNN-Connect/DNN-Translator#8]
Fork, Clone, open .sln with VS2019, build. Does not build, because of errors:

`Error	BC30002	Type 'ZipOutputStream' is not defined.	Translator	C:\DDrive\Develop\GitHub\DNN-Translator\Services\Packing\LanguagePack.vb	57	Active`

And several warnings

**Comment by donker** [comment]
Solved in 1.2.1

**Comment by EPTamminga** [comment]
What am I doing wrong?
I do a Fork, Clone, Open Solution in VS2019.  I get a message of a not supported project (Setup).
I do a Build/Clean Solution, Build. And bingo:

![image](https://user-images.githubusercontent.com/5859855/82043129-5356e880-96ab-11ea-87c3-337d2049e55e.png)

**Comment by donker** [comment]
You need restore nuget packages and either install the setup project under extensions (this is now a separate install in VS) or just exclude the setup project from the solution (which you probably don't need).

**Comment by EPTamminga** [comment]
@donker Which Installer do you use?

I removed the setup project + I had to remove/add a new reference to system.net.http.dll, now it builds.

**Comment by donker** [comment]
What I should do is to remove the installer from the main project. It is not really meant for anyone else unless you wish to distribute the app which would create confusion.

But this is the extension:

![Screenshot 2020-05-26 at 12 23 50](https://user-images.githubusercontent.com/3319692/82889955-c7b34680-9f4b-11ea-8dd2-99d8640da2f0.png)

**Comment by EPTamminga** [comment]
I agree. Just remove the setup project and make it a separate (private?) solution?

**Comment by david-poindexter** [comment]
@donker regarding the installer, I ran into a similar issue with nvQuickSite and ultimately decided to include the installer project.
