### ISSUE TITLE
New version changes lastModified date for keys that have not been touched

### ISSUE THREAD

**Issue by vmasanas** [DNN-Connect/DNN-Translator#9]
I've edited a few entries on a file and now a bunch of them say that have been modified.
notice that it seesm to change only the hour fraction of the date:

![image](https://user-images.githubusercontent.com/4357679/81921722-571b3a00-95db-11ea-908c-e8107c6719bf.png)

**Comment by EPTamminga** [comment]
@vmasanas TimeZone issue?

**Comment by donker** [comment]
Solved in 1.2.1
